version: '3'
services:
   haproxy:
      image: haproxytech/haproxy-debian:2.5.0
      command: -f /opt/haproxy -f /opt/haproxy2
      volumes: 
      - "./conf:/opt/haproxy"
      - "./conf2:/opt/haproxy2"
      - "./iplist.lst:/etc/haproxy/iplist.lst"
      ports:
      - "9000:9000"
      - "5000:5000"
      - "5001:5001"
   web:
      image: nginx